### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by kevincovey** [jradavenport/spot-colors#1]
- [x] KRC find spectral models, send to JRAD 
  (The R~10,000 model grid at http://phoenix.astro.physik.uni-goettingen.de/?page_id=16 would be my recommended starting point)
## Pre NYC HW
- [ ] KRC find a couple K2 light curves to model (grab Upper Sco from disk, Pleiades from web)
- [x] KRC install pysynphot
- [x] KRC (+JRAD?) stash R~10,000 model grid on laptop
## Goals for NYC
- [x] JRAD make filter curves uniform in units
- [x] JRAD look in `astropy` for filter convolution, else write filter convolution method up (or just use pysynphot?; completed under assumption that pysynphot does work.)
- [x] develop routine to read in synthetic spectrum based on desired parameters.
- [x] develop routine to calculate synthetic photometry from a given input synthetic spectrum (basically just feeding synthetic spectrum to pysynphot, and/or asking Dr. Larson for her python routines that do this)
- [x] develop routine to read in MULTIPLE spectra based on desired individual parameters, then combine them into a single spectrum using the requested filling factors
- [x] develop routine to generate standard photometric colors (UBVRI/ugriz/JHK/Kepler_mag, all with meaningful relative zeropoints) for specified filling factor, T_phot, & temperature contrast
- [x] develop routine to place colors on meaningful absolute scale based on input stellar radius and distance.
- [ ] use model framework to identify range of filling factors and temperature contrast needed to reproduce the spread in the Pleiades' cluster sequence in the V-K vs. V color-magnitude diagram (i.e., Figure 1) in the Pleiades paper. 
- [ ] develop routine identify degenerate combination of (asymmetric) filling factor and temperature contrast that can reproduce a given input Kepler light curve [not clear what the natural timescale for this determination is, actually;  probably need to refine goal a bit.]

**Comment by jradavenport** [comment]
Yes - let us do the things!

**Comment by kevincovey** [comment]
Possible solution for synthetic photometry: see http://ssb.stsci.edu/pysynphot/docs/

**Comment by jradavenport** [comment]
Awesome! pysynphot was an easy install via pip:

```
pip install pysynphot
```

now to see if it works for us

**Comment by jradavenport** [comment]
Which version of the model grid should we grab? I'm looking at the FTP link for the R10000 files. Are we happy with:
`PHOENIX-ACES-AGSS-COND-2011_R10000FITS_Z-0.0.zip` ?
